name: Security Scanning

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

# As always, follow the principle of least privilege:     
permissions:
  # Read only access to repository content such as commits, branches, releases and so on.
  contents: read
  # Permissions for GitHub Actions to upload SARIF results:
  security-events: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      #- run: echo "Implement semgrep scanning"
      - uses: actions/checkout@v4
      - name: Run Semgrep  
        run: |
          semgrep scan \
          --config p/default \
          --include todo-app/ \
          --sarif \
          --output semgrep.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif


  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Implement trivy scan"

  truffle:
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
      - run: echo "Implement trufflehog scan"
